language: java
jdk:
  - oraclejdk11
before_install:
  - chmod +x ./gradlew
  - chmod +x ./gradle/wrapper/gradle-wrapper.jar
script:
  - ./gradlew clean test --stacktrace
  - /gradlew sonarqube \
    -Dsonar.projectKey=PiotrZlotowski_DiscoverNow \
    -Dsonar.organization=piotrzlotowski-github \
    -Dsonar.host.url=https://sonarcloud.io \
    -Dsonar.login=$SONAR_TOKEN