version: '3'
services:
  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    volumes:
    - /var/lib/postgresql
    container_name: "postgres"
  mail:
    image: tophfr/mailcatcher
    ports:
      - "1080:80"
      - "2025:25"
    container_name: "mail"